# Generated by Django 3.2.8 on 2021-11-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام مرکز')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='کد گروه کالا')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام گروه کالا')),
            ],
        ),
        migrations.CreateModel(
            name='CenterTargetDefinde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qnty', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'Farvardin'), (2, 'Ordibhesht'), (3, 'Khordad'), (4, 'Tir'), (5, 'Mordead'), (6, 'Shahrivar'), (7, 'Mehr'), (8, 'Aban'), (9, 'Azar'), (10, 'Day'), (11, 'Bahman'), (12, 'Esfand')])),
                ('Pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.productgroup', verbose_name='گروه محصول')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd', verbose_name='مرکز توزیع')),
            ],
        ),
        migrations.AddField(
            model_name='centerd',
            name='products_group',
            field=models.ManyToManyField(to='targets.ProductGroup'),
        ),
    ]
