# Generated by Django 3.2.8 on 2022-07-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام مرکز')),
            ],
            options={
                'verbose_name': 'مرکز توزیع',
                'verbose_name_plural': 'مرکز توزیع ها',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='کد گروه کالا')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه محصولات',
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'گروه فروش',
                'verbose_name_plural': 'گروههای فروش',
            },
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd')),
            ],
            options={
                'verbose_name': 'سرپرست',
                'verbose_name_plural': 'سرپرست ها',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('cneter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='targets.saleline')),
                ('superviser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='targets.superviser')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='TargetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centers', models.ManyToManyField(to='targets.CenterD', verbose_name='مراکز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'دسترسی اهداف',
                'verbose_name_plural': 'دسترسی های اهداف',
            },
        ),
        migrations.AddField(
            model_name='centerd',
            name='lines',
            field=models.ManyToManyField(to='targets.SaleLine'),
        ),
        migrations.AddField(
            model_name='centerd',
            name='products_group',
            field=models.ManyToManyField(to='targets.ProductGroup'),
        ),
        migrations.CreateModel(
            name='SetVisitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهرویور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('qnty', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.productgroup')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.visitor')),
            ],
            options={
                'verbose_name': 'تعریف هدف',
                'verbose_name_plural': 'تعریف اهداف',
                'unique_together': {('month', 'visitor', 'pgroup')},
            },
        ),
        migrations.CreateModel(
            name='CenterTargetDefinde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qnty', models.IntegerField()),
                ('accept', models.BooleanField(default=False)),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهرویور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('Pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.productgroup', verbose_name='گروه محصول')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd', verbose_name='مرکز توزیع')),
            ],
            options={
                'verbose_name': 'اهداف مرکز توزیع',
                'verbose_name_plural': 'اهداف مراکز توزیع',
                'unique_together': {('center', 'Pgroup', 'month')},
            },
        ),
    ]
