# Generated by Django 3.2.8 on 2021-11-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='centerd',
            options={'verbose_name': 'مرکز توزیع', 'verbose_name_plural': 'مرکز توزیع ها'},
        ),
        migrations.AlterModelOptions(
            name='centertargetdefinde',
            options={'verbose_name': 'اهداف مرکز توزیع', 'verbose_name_plural': 'اهداف مراکز توزیع'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'گروه محصول', 'verbose_name_plural': 'گروه محصولات'},
        ),
        migrations.AlterField(
            model_name='centertargetdefinde',
            name='month',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهرویور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه'),
        ),
        migrations.AlterUniqueTogether(
            name='centertargetdefinde',
            unique_together={('center', 'Pgroup', 'month')},
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cneter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd')),
                ('superviser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='targets.superviser')),
            ],
        ),
        migrations.AddField(
            model_name='superviser',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.centerd'),
        ),
        migrations.CreateModel(
            name='SetVisitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField()),
                ('pgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.productgroup')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.visitor')),
            ],
        ),
    ]
