# Generated by Django 3.2.8 on 2022-07-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGroup',
            new_name='ProductTargetGroup',
        ),
    ]
