# Generated by Django 3.2.8 on 2021-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20211125_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='setvisitortarget',
            name='month',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهرویور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], default=1, verbose_name='ماه'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='setvisitortarget',
            unique_together={('month', 'visitor', 'pgroup')},
        ),
    ]
