# Generated by Django 3.2.8 on 2021-11-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_auto_20211125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerd',
            name='lines',
            field=models.ManyToManyField(to='targets.SaleLine'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='targets.saleline'),
            preserve_default=False,
        ),
    ]
