# Generated by Django 3.2.8 on 2021-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_auto_20211125_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleline',
            options={'verbose_name': 'گروه فروش', 'verbose_name_plural': 'گروههای فروش'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
