# Generated by Django 3.2.8 on 2021-11-26 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0006_auto_20211125_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerd',
            options={'ordering': ('code',), 'verbose_name': 'مرکز توزیع', 'verbose_name_plural': 'مرکز توزیع ها'},
        ),
        migrations.CreateModel(
            name='TargetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centers', models.ManyToManyField(to='targets.CenterD', verbose_name='مراکز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'دسترسی اهداف',
                'verbose_name_plural': 'دسترسی های اهداف',
            },
        ),
    ]
