# Generated by Django 3.2.8 on 2021-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_auto_20211126_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='setvisitortarget',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
