# Generated by Django 3.2.8 on 2021-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_setvisitortarget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='centertargetdefinde',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
