# Generated by Django 3.2.8 on 2021-10-29 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 29, 18, 12, 27, 564824))),
                ('eventDate', django_jalali.db.models.jDateTimeField()),
                ('description', models.TextField()),
                ('affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.center')),
                ('effected', models.ManyToManyField(related_name='effected', to='events.Center', verbose_name='Effected')),
            ],
        ),
    ]
