# Generated by Django 3.2.8 on 2022-07-26 17:51

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 7, 26, 22, 21, 22, 134857), verbose_name='زمان ذخیره'),
        ),
        migrations.AlterField(
            model_name='messageerror',
            name='time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 7, 26, 22, 21, 22, 139855)),
        ),
    ]
