# Generated by Django 3.2.8 on 2021-10-29 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'مرکز', 'verbose_name_plural': 'مراکز'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'واقعه', 'verbose_name_plural': ' وقایع'},
        ),
        migrations.AddField(
            model_name='event',
            name='firstAccept',
            field=models.BooleanField(default=False, verbose_name='تایید اولیه'),
        ),
        migrations.AddField(
            model_name='event',
            name='secendAccept',
            field=models.BooleanField(default=False, verbose_name='تایید دوم'),
        ),
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='event',
            name='affected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.center', verbose_name='واحد تاثیر گذار'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='شرح واقعه'),
        ),
        migrations.AlterField(
            model_name='event',
            name='effected',
            field=models.ManyToManyField(related_name='effected', to='events.Center', verbose_name='واحدهای تاثیر پذیر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان واقعه'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 29, 20, 42, 31, 315687), verbose_name='زمان ذخیره'),
        ),
    ]
