# Generated by Django 3.2.8 on 2021-10-29 18:01

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211029_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=0, max_length=225, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 29, 21, 31, 31, 961411), verbose_name='زمان ذخیره'),
        ),
    ]
