# Generated by Django 3.2.8 on 2021-10-29 18:17

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 29, 21, 47, 45, 532292), verbose_name='زمان ذخیره'),
        ),
    ]
