# Generated by Django 3.2.8 on 2021-11-12 15:01

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211110_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='isManagerAffect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='isManagerEffect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description2',
            field=models.TextField(null=True, verbose_name='شرح واقعه گذار'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='شرح واقعه تاثیر پذیر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 12, 18, 30, 59, 849241), verbose_name='زمان ذخیره'),
        ),
    ]
