# Generated by Django 3.2.8 on 2021-11-12 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20211112_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='isManagerAffect',
            new_name='isManager',
        ),
        migrations.RemoveField(
            model_name='access',
            name='isManagerEffect',
        ),
        migrations.AddField(
            model_name='access',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MANAGER', to='auth.user', verbose_name='نام مدیر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='affect',
            field=models.ManyToManyField(to='events.Center', verbose_name='مراکز تاثیر پذیر زیر مجموعه'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 12, 20, 1, 45, 872954), verbose_name='زمان ذخیره'),
        ),
    ]
