# Generated by Django 3.2.8 on 2021-11-12 17:55

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واقعه گذار'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 12, 21, 25, 41, 618431), verbose_name='زمان ذخیره'),
        ),
    ]
