# Generated by Django 3.2.8 on 2021-11-12 19:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20211112_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 12, 23, 24, 37, 374032), verbose_name='زمان ذخیره'),
        ),
    ]
