# Generated by Django 3.2.8 on 2021-11-19 12:29

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211112_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 19, 15, 59, 21, 180536), verbose_name='زمان ذخیره'),
        ),
    ]
