# Generated by Django 3.2.8 on 2021-11-25 17:24

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 25, 20, 53, 53, 385527), verbose_name='زمان ذخیره'),
        ),
    ]
