# Generated by Django 3.2.8 on 2021-11-26 09:38

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 26, 13, 8, 13, 618015), verbose_name='زمان ذخیره'),
        ),
    ]
