# Generated by Django 3.2.8 on 2021-11-28 16:29

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 11, 28, 19, 59, 30, 636136), verbose_name='زمان ذخیره'),
        ),
    ]
