# Generated by Django 3.2.8 on 2021-12-02 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_alter_event_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 2, 22, 40, 21, 104248), verbose_name='زمان ذخیره'),
        ),
        migrations.CreateModel(
            name='MessageError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 2, 22, 40, 21, 111250))),
                ('message', models.TextField(max_length=5000)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
