# Generated by Django 3.2.8 on 2021-12-02 19:40

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20211202_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageerror',
            name='inprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageerror',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 2, 23, 10, 48, 261874), verbose_name='زمان ذخیره'),
        ),
        migrations.AlterField(
            model_name='messageerror',
            name='time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 2, 23, 10, 48, 265872)),
        ),
    ]
