# Generated by Django 3.2.8 on 2021-12-03 15:32

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20211202_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 3, 19, 2, 45, 989645), verbose_name='زمان ذخیره'),
        ),
        migrations.AlterField(
            model_name='messageerror',
            name='time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 3, 19, 2, 46, 639)),
        ),
    ]
