# Generated by Django 3.2.8 on 2021-12-03 18:00

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20211203_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_visitors_target_without_center_target', models.BooleanField(verbose_name='امکان اضافه کردن اهداف ویزیتورها بدون هدف مرکز')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 3, 21, 30, 39, 255582), verbose_name='زمان ذخیره'),
        ),
        migrations.AlterField(
            model_name='messageerror',
            name='time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 3, 21, 30, 39, 261579)),
        ),
    ]
