# Generated by Django 3.2.8 on 2021-12-18 07:33

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20211217_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recordDate',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 18, 11, 3, 48, 330471), verbose_name='زمان ذخیره'),
        ),
        migrations.AlterField(
            model_name='messageerror',
            name='time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 12, 18, 11, 3, 48, 330471)),
        ),
    ]
