# Generated by Django 3.2.8 on 2022-07-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_productgroup_producttargetgroup'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='product_target_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='targets.producttargetgroup'),
            preserve_default=False,
        ),
    ]
